### ISSUE TITLE
Clicking show details opens another application in Gnome Software (Glimpse).

### ISSUE THREAD

**Issue by marco4mp** [flathub/org.gimp.GIMP#120] opened 2021-10-21 23:05 UTC
Hi. 
Clicking show details opens another application in Gnome Software, specifically Glimpse.
I use a lot of Flathub apps, this only happens with Gimp.

Video example:

https://user-images.githubusercontent.com/52709674/138367685-81a11caf-8552-4129-be19-f58f4e186f6a.mp4

GIMP 2.10.28 (Flathub)
Fedora 34, Gnome 40.

**Comment by marco4mp** [comment] 2021-10-23 00:08
.

**Comment by brunvonlope** [comment] 2024-05-18 22:52
According to my tests in Fedora 40 (GNOME 46), "Show details" from right click in the applications list opens GIMP on GNOME Software. 

Also,"Show details" from the top shell (and the overall global menu) was dropped in some GNOME version, and Glimpse was archived in [2023](https://github.com/flathub/org.glimpse_editor.Glimpse). So, closing as obsolete.

**Closed by brunvonlope** 2024-05-18 22:52 UTC
Labels: 2. Not GIMP

**Comment by Jehan** [comment] 2024-05-20 08:27
The problem was not necessarily about Glimpse, but about how About works (which was broken in specific conditions?). So it being archived doesn't mean that the bug is fixed because we haven't found the real cause for this bug.

This being said, I think nobody ever managed to reproduce since the first report and we don't have a single lead so far (nobody is actively investigating either AFAIK). So ok, let's leave it closed. If this issue ever reproduces again though, do not hesitate to reopen or open a new report.
