### ISSUE TITLE
Gimp (Flatpak) does not appear in the software center.

### ISSUE THREAD

**Issue by alexb3d** [flathub/org.gimp.GIMP#14] opened 2018-05-14 18:33 UTC
Gimp (Flathub) does not appear in the software center.

**Comment by Jehan** [comment] 2018-05-14 18:35
Thanks for the report. This is a duplicate of #12, which is most likely itself a duplicate of #8. So I'll close. You should subscribe to #12 if you wish to follow any evolution of the situation.

**Closed by Jehan** 2018-05-14 18:35 UTC
