### ISSUE TITLE
GIMP is nowhere to be found in Gnome-Software

### ISSUE THREAD

**Issue by brittyazel** [flathub/org.gimp.GIMP#18] opened 2018-05-21 19:33 UTC
I just wanted to let you guys know that Gnome-Software shows me just about every app on flathub, except for GIMP it seems. No matter how I search it, I can't find it there.

**Comment by Jehan** [comment] 2018-05-21 19:37
Thanks for the report.
We know about this issue which is being investigated. I also opened this report on flatpak side to get the flatpak devs help since we are not sure at all where the problem is from (is it our metadata, or flatpak, or flathub or else?): https://github.com/flatpak/flatpak/issues/1696

I will close this issue since it is basically a duplicate of other reports. :-)

**Closed by Jehan** 2018-05-21 19:37 UTC
