### ISSUE TITLE
Update keeps failing (2.10.14)

### ISSUE THREAD

**Issue by Olaf987** [flathub/org.gimp.GIMP#63] opened 2019-11-16 13:44 UTC
Dear all:

When I try to update I get the following error:

`olaf@olaf-devil:~$ flatpak update
Looking for updates...
Updating in system:
org.gimp.GIMP/x86_64/stable flathub 8003d469b222
Is this ok [y/n]: y
Updating: org.gimp.GIMP/x86_64/stable from flathub
[####################] Downloading: 3,3 MB/3,3 MB (3,3 MB/s)
Error: Failed to update org.gimp.GIMP/x86_64/stable: While pulling app/org.gimp.GIMP/x86_64/stable from remote flathub: opcode close: Corrupted file object; checksum expected='caa81b53ed55fc5b298b5c820a8387372ef2b0c511f9f7b54fcadf1cfdd6dcf3' actual='edc797565295886537fa049cbc39000143e5848f78d75f898c93b5181714b35a'
error: There were one or more errors
olaf@olaf-devil:~$ `

I have no clue what I can do about this.

**Comment by Jehan** [comment] 2019-11-16 14:47
Have you tried several times? With the checksum error, it looks like it could just be a corrupted download (i.e. if you retried, it could work fine).

Other than this I have no idea either. As you can guess, this is not a bug in GIMP but either in [flatpak](https://github.com/flatpak/flatpak) or in the [flathub](https://github.com/flathub/flathub) server (or ultimately a MitM, i.e. whatever you are pulling, it's not the GIMP we built). I would suggest to go and ask there.

Write down the flatpak version you are using when you report your issue there.

**Comment by Jehan** [comment] 2020-02-08 13:51
Did you end up reporting the issue to flatpak or flathub project? Or did it finally work?

Anyway closing this report as this is not a bug within our package. It's something else, and if you still have the issue, report to one of the aforementioned projects.

**Closed by Jehan** 2020-02-08 13:51 UTC

**Comment by Olaf987** [comment] 2020-02-09 16:13
Sorry

I lost track of this particular issue. Linux Mint was renewed in the mean time (19.2 -> 19.3). I will keep an eye on it.
