### ISSUE TITLE
Where should 3rd party plugins install?

### ISSUE THREAD

**Issue by bootchk** [flathub/org.gimp.GIMP#22] opened 2018-06-04 22:30 UTC
I just installed 2.10.2 from flatpak onto Ubuntu 17.10.  Then I built resynthesizer (a set of 3rd party plugins, some compiled C, some .py) from its origin, which uses automake toolchain a la the ancient gimp-plugin-template. It installed, but GIMP didn't find it.  Even after I added the path to the installed locations to Edit>Preferences>Folder>Plugins and restarted.  GIMP only found it when I installed to the ~/.vars/..../plug-ins (the sandbox?).  Also, I don't understand the second location in the default plugin paths: "/app/lib/gimp/2.0/plug-ins" since my machine doesn't have an /app dir.  I expected the old path "~/gimp2.<x>/plug-ins" in the list of default plugin paths.  I could easily have made a mistake though.

What is the recommended location for installing 3rd party plugins?  If installed to the first default location, will they be trashed by an update to GIMP?  If should be installed to the second default location, where is it (what is the absolute path?)  If should be installed to a third location, will GIMP ever default to searching it, or will the user always need to add plugin paths preferences?

(I did see the other issue about flatpaks for 3rd party plugins.  I am considering building such a flatpak for resynthesizer, it that is necessary, or wait til another 3rd party plugin such as G'mic does similar.)

(I am new to flatpaks and XDG but have some experience with sandboxes on OSX)

**Comment by supertobi** [comment] 2018-07-13 12:16
GIMP should add an extension point for plugins and then you could build the plugin as a
flatpak extension. I think every thing else will lead to problems.
Have a look into this blog post:
https://blog.tingping.se/2018/03/18/flatpaking-plugins.html

**Comment by Jehan** [comment] 2018-07-13 13:54
Please feel free to make a merge request for our manifest allowing such feature. If you could also provide an example GIMP plug-in as flatpak extension as a separate manifest for me to test if this works, it would waste less time.

**Comment by supertobi** [comment] 2018-07-19 18:58
I have here a example script an the extended org.gimp.GIMP.json. In the org.gimp.GIMP.json I've added the section "add-extensions" and in the modules part I've added a directory where I install the scripts:
```
    "add-extensions": {
        "org.gimp.GIMP.Script": {
        "version": "2",
        "directory": "extensions",
        "merge-dirs": "merge",
        "subdirectories": true,
        "no-autodownload": true,
        "autodelete": true
        }
...
      {
            "name": "extensionScripts",
            "buildsystem": "simple",
            "build-commands": [
                "install -d /app/extensions/."
            ]
        }
```
The example script is placed in the folder "/app/extensions/AlienGlow/"

![bildschirmfoto von 2018-07-19 20-54-20](https://user-images.githubusercontent.com/653976/42964009-2451ce00-8b96-11e8-99e4-f3cd986b6535.png)

@Jehan  The problem is now does the script does not get loaded, and I don't know why. I even don't know how to debug it. :( Now I need some help from a real developer.

[gimp_script.zip](https://github.com/flathub/org.gimp.GIMP/files/2211279/gimp_script.zip)
[org.gimp.GIMP.zip](https://github.com/flathub/org.gimp.GIMP/files/2211283/org.gimp.GIMP.zip)

**Comment by supertobi** [comment] 2018-07-19 19:14
Update: It gets loaded, I just looked at the wrong place.

**Comment by supertobi** [comment] 2018-07-19 19:23
And here is a very basic flatpak example with two extensions. That is very helpful for testing, without needing to wait for the build to long:
[flatpak_test.zip](https://github.com/flathub/org.gimp.GIMP/files/2211370/flatpak_test.zip)

**Comment by bootchk** [comment] 2019-06-04 23:50
I am attempting to test this with GIMP and resynthesizer.  Resynthesizer is C code, builds with autotools, against libgimp-2.0 (and other libs such as glib.)  (More than just copying a text file to an install directory, as in the examples in this thread.)

What should the  "sdk": value be for a flatpak'ed extension?

Here is resynthesizer.json

`{
  "id": "org.gimp.GIMP.Plugin.resynthesizer",
  
  "branch": "stable",
    "runtime": "org.gimp.GIMP",
    "runtime-version": "2.10",
    "sdk": "org.gimp.Sdk",
    "command": "gimp-2.10",
  "build-extension": true,
  "separate-locales": false,
  "appstream-compose": false,
  
  "modules": [
     {
       "name": "Resynthesizer",
       "buildsystem": "autotools",
       "sources": [
                {
                    "type": "git",
                    "url": "https://github.com/bootchk/resynthesizer.git",
                    "branch": "master",
                    "commit": "adfa25ab0d11ed27ff301cb7db4b144c4c2fa112"
                }
       ]           
     }
  ]
}`

I get: Failed to init: Unable to find sdk org.gimp.Sdk version 2.10

I think I have successfully flatpak built GIMP with an extension point.

Also, will flatpak invoke the autotools install commands, or do I need more in the plugin's flatpak manifest to do the install to the extension point directory?

**Comment by supertobi** [comment] 2019-06-05 07:02
I think the best thing is to ask in the flatpak mailinglist. There are the real experts.

**Comment by Jehan** [comment] 2019-06-05 11:10
> I get: Failed to init: Unable to find sdk org.gimp.Sdk version 2.10

Well error is pretty clear: it tries to install `org.gimp.Sdk` and fails. In your manifest you are indeed telling it to build your plug-in based on such SDK. The fact is that I don't think this package exist at all. So basically the bug is in your manifest.

In any case, @supertobi is right. Please ask your question to flatpak mailing list, IRC or whatnot. You probably know as much as we do.

@supertobi by the way, we are still by this extension point. If ever you get to a point where it just works, feel free to propose a patch.

**Comment by bootchk** [comment] 2019-06-05 13:39
Yes, I will ask elsewhere.  Maybe there is an example in flathub already.

If I get it to work, I might also submit a patch to the GIMP stable json.

However you might want to think about names of the directories for extensions and when they are created.  As far as I can tell, for the flatpak GIMP, the directories ./var/app/org.gimp.GIMP/config/GIMP/2.10 such as /scripts and /plug-ins are already created (but empty.) I presume they are for third parties and that GIMP supported plugins and scripts are elsewhere.  I don't know how they were created by the existing GIMP json, and whether the patch suggested by supertobi and tingping is creating a directory called "extensions".

**Comment by Jehan** [comment] 2019-06-05 13:47
> the directories ./var/app/org.gimp.GIMP/config/GIMP/2.10 such as /scripts and /plug-ins are already created (but empty.) I presume they are for third parties and that GIMP supported plugins and scripts are elsewhere.

These are user-directories, i.e. for user-installed scripts/plug-ins. Yet flatpak-installed extensions would have to be considered system plug-ins and scripts. These would have to be respectively under `/app/lib/gimp/2.0/plug-ins/` and `/app/share/gimp/2.0/scripts/` in the flatpak environment.

**Comment by bootchk** [comment] 2019-06-05 14:31
@supertobi  Your example for the alien-glow.scm plugin does not include a .json (for building the extension/plugin)   Is that an omission?  As far as I understand, your scripts are for the case where gimp.org would include all the extensions (such as .scm scripts) in their build and their json installs them.  The use case here is  org.gimp declares the extension point in their .json and a  third party (e.g. myself, or gmic.org) defines a separate .json flatpak manifest that can be flatpak'ed to build and install the third party plugin.

**Comment by bootchk** [comment] 2019-06-05 21:02
I made progress.  Seems that sdk should be "org.gnome.Sdk//3.32".

However, now when building my plugin I get: 
    checking for GIMP... no
    configure: error: GIMP development libraries not found; please install.

A dependency of my plugin (any C Gimp plugin) is libgimp-2.0.  It seems that flatpaking GIMP doesn't  install that.  I am wondering how to proceed, to add libgimp as a module of my plugin in my json flatpak manifest, or some other solution.

**Comment by Jehan** [comment] 2019-06-05 22:03
Indeed we clean out all dev files (i.e. headers and pkg-config files used for dependency discovery). I guess any patch adding an extension point should clean all dev files except GIMP ones.

Or maybe even we should clean no development files at all to allow every plug-in out there to build against all the libraries we include in our flatpak (header and pc files are just text files anyway; I don't think it would take that much additional space).

Anyway have a look at the "cleanup" field in GIMP flatpak.

**Comment by bootchk** [comment] 2019-06-05 22:28
Yes, it is the .h header that is missing I think.  I will try your idea.  But it seems like a hole in the flatpak extension idea, i.e. shouldn't the .h file be part of the non-existent org.gimp.SDK, or more generally, an SDK for any app to which extensions can be built.

I know you might be working on a resource manager for GIMP.   Thanks.  The resynthesizer flatpak problem is small, I know users can just build and copy, or rely on distributions to build it.

**Comment by supertobi** [comment] 2019-06-06 09:04
> @supertobi by the way, we are still by this extension point. If ever you get to a point where it just works, feel free to propose a patch.

I somehow had the feeling, that no one is really interested and so I moved this at the end of my ToDo list. But now that @bootchk  is working on it I'll try to find some time for it. (But don't expect to much.)

> @supertobi Your example for the alien-glow.scm plugin does not include a .json (for building the extension/plugin) Is that an omission? As far as I understand, your scripts are for the case where gimp.org would include all the extensions (such as .scm scripts) in their build and their json installs them. The use case here is org.gimp declares the extension point in their .json and a third party (e.g. myself, or gmic.org) defines a separate .json flatpak manifest that can be flatpak'ed to build and install the third party plugin.

I switched from the real GIMP flatpak to a smaller test project. Have a look at flatpak_test.zip. This made the creation of the flatpaks much faster.

>But it seems like a hole in the flatpak extension idea, 
Flatpak extension are far from perfect. That's why you should get in closer contact with the flatpak developers. 

> The resynthesizer flatpak problem is small, I know users can just build and copy, or rely on distributions to build it.

Please don't underestimate your work. At least I think its important. And I think the extension manager from @Jehan still needs a lot of work until an user is able to install binary plugins with it.

**Comment by Jehan** [comment] 2019-06-06 09:39
> I somehow had the feeling, that no one is really interested and so I moved this at the end of my ToDo list.

It's just not my own priority right now (or before), which means I didn't want to spend too much time on it myself. That doesn't mean I (or we, considering the team and the whole community) am not interested if someone does the heavy lifting (any or both of you!). :-)

> I know you might be working on a resource manager for GIMP. Thanks.

Yeah but the work on resource manager is at another level (for this first step). It is about how to distribute, version, install, update, etc. resources. In particular I am not touching how plug-ins are run. So the same issues will arise in flatpak/snap/appimage/whatever-else even with the resource manager. I would love to think a bit more on our plug-in running system later. But that will be a later step.

**Comment by bootchk** [comment] 2019-06-06 15:09
The line in resynthesizer's configure.ac that throws an error when trying to flatpak:

PKG_CHECK_MODULES(GIMP,
  gimp-2.0 >= $GIMP_REQUIRED_VERSION gimpui-2.0 >= $GIMP_REQUIRED_VERSION,
,AC_MSG_ERROR(GIMP development libraries not found; please install.))

I already tried to flatpak GIMP without deleting /include directory, and I still get the same error.  So it is not just searching for the .h header, it is examining installed packages.  I don't really know autotools or package manager or whether flatpak uses it when it installs GIMP.  Still exploring....

**Comment by Jehan** [comment] 2019-06-06 17:47
Yeah I told you the answer to this 2 messages of mine ago. :-)

You need also to keep the pkg-config files (`.pc`). These are in `/lib/pkgconfig` and `/share/pkgconfig`.

**Comment by bootchk** [comment] 2019-06-07 14:22
Sorry.

Fixing GIMP.json to not cleanup does not solve issue.  I think  the build environment for the extension does not refer to the flatpak GIMP's artifacts such as .pc files .  I think my extension.json needs  "build-options" e.g. to modify pkg-config-path (and maybe prefix?)  I was assuming that was automatic once I declared "runtime": "org.gimp.GIMP".

The ONLY example of flatpak extension seems to be TingPing's blog.  Where he seems to say that build-options are not automatic.  So I am hacking at the build-options.

**Comment by bootchk** [comment] 2019-06-14 14:42
An update on lack of progress.

TingPing's example builds the extension inside the manifest (.json) of the app (parent of the extension, in that case HexChat, in my case GIMP.)

To follow that example, I hacked the gimp.json to get only the relevant part that my C extension needs (libgimp-2.0).  That was unsuccessful, symptom was missing  macro AM_PATH_GTK_2_0.  (Since libgimp and libgimpui are built at the same time, and libgimpui depends on GTK?  I wish it were not so.)  Even if I could get it to work, I don't understand flatpak manifest well enough to ensure that my extension manifest would not bundle libgimp also, instead of just installing the extension in the right place.  Maybe I should add my extension to the entire gimp.json, and see what bundle that creates.

Also failed to get a standalone .json working, using BUILD-OPTIONS to point to needed headers and packages.  I don't know whether a flatpak build itself is sandboxed and can't see outside into the installed GIMP, or whether flatpak even updates pkgconfig (referenced by my configure script) 

I am not actively working on the problem, its more important to address other issues with resynthesizer, such as GIMP 3.0/GEGL compatibility.

**Comment by hfiguiere** [comment] 2020-06-12 04:12
I'll submit a PR soon for resynthesizer once #75 is squared up. It currently works locally.

**Comment by hfiguiere** [comment] 2020-06-13 13:31
Resynthesizer is pending.

**Comment by Jehan** [comment] 2020-06-21 12:57
The extension point has now been added to the flatpak and this is now live. Various plug-in manifests are still being reviewed but now we can say that the method exists. So let's close this! 🥳

**Closed by Jehan** 2020-06-21 12:57 UTC
