### ISSUE TITLE
Not visible in GNOME Software

### ISSUE THREAD

**Issue by jurf** [flathub/org.gimp.GIMP#12] opened 2018-05-08 13:27 UTC
Original report: https://twitter.com/alexb3d/status/992538697252864000

I can confirm, running F28, GS 3.28.

**Comment by TingPing** [comment] 2018-05-08 14:08
`pkill gnome-software && gnome-software --verbose`

**Comment by jurf** [comment] 2018-05-08 15:00
[gs-no-gimp.log](https://github.com/flathub/org.gimp.GIMP/files/1984459/gs-no-gimp.log)

**Comment by TingPing** [comment] 2018-05-08 16:11
Logs show it finding it just fine.

**Comment by jurf** [comment] 2018-05-08 17:57
Definitely doesn’t show though, even with `env LANG=C`.

**Comment by TingPing** [comment] 2018-05-08 20:37
Seems like a duplicate of #8

**Comment by Lvaskz** [comment] 2018-05-10 20:47
Yes same problem, gimp not shows in gnome software ubuntu 18.04

**Closed** 2018-05-15 07:00 UTC
