### ISSUE TITLE
Toolbox icons have huge padding

### ISSUE THREAD

**Issue by SakiiCode** [flathub/org.gimp.GIMP#278] opened 2024-02-03 13:19 UTC
In the flatpak version the tool buttons have unreasonably high padding and take up a lot of space.
Both screenshots were taken with the Legacy icon theme, with Medium size, but applies to all icon themes.
I would say the Flatpak+Color+Small is close to Native+Legacy+Medium, but these should be standardized.

![gimp_icons](https://github.com/flathub/org.gimp.GIMP/assets/13037299/9c12709b-c47a-4272-9232-c8d20cbcb266)

Flatpak GIMP version: 2.10.36
Native GIMP version: 2.10.30
OS: Linux Mint 21.2

**Comment by Jehan** [comment] 2024-02-15 00:24
I have no idea here. I think we haven't touch such part of the code for years in the 2.10 series. If anyone has any suggestion on what could be the difference, feel free to weigh in.

**Comment by brunvonlope** [comment] 2024-05-15 14:51
The unpredictable padding on Legacy icon theme is caused by the lack of bigger sizes.

Closing as duplicate of: https://gitlab.gnome.org/GNOME/gimp/-/issues/887

**Closed by brunvonlope** 2024-05-15 14:51 UTC
