### ISSUE TITLE
GIMP wrong tastkbar icon

### ISSUE THREAD

**Issue by marcogiannini** [flathub/org.gimp.GIMP#89] opened 2020-10-14 13:14 UTC
GIMP installation on KDE I could notice that the icon in the task manager is different from the launcher icon. The icon present in the task manager is monochrome instead of the standard GIMP icon.
![Screenshot_20201014_151059](https://user-images.githubusercontent.com/4943897/95993911-f5802580-0e2f-11eb-9db8-c419482605e9.png)

**Comment by Jehan** [comment] 2020-10-14 13:45
That's because the taskbar icon uses the icon from the theme (in your case, you use the symbolic theme) whereas the menu icon uses an icon specified in the desktop file (which does not change whatever icon theme was chosen in Preferences).

I'm not so sure there are really any (good) solutions, or if this "issue" really can really be called a bug. But I would not refuse a patch if there is a proper solution to this inconsistency. Why not.

Though if you really want this fixed, could you please open the report at: https://gitlab.gnome.org/GNOME/gimp/-/issues

This is not about the flatpak. It's true however you installed GIMP. So this report should go in the main bugtracker.

P.S.: also it's not KDE only, I see the same thing in GNOME for instance.

**Comment by Jehan** [comment] 2020-10-25 10:35
Anyway let's close this. As said in my previous comment, this is not a bug in the flatpak at the very least so there is no need to keep this opened forever. If you really feel this is wrong, please open a report in [our main bugtracker](https://gitlab.gnome.org/GNOME/gimp/-/issues) so that more people are able to see this, and maybe someone will have a solution to give. Who knows.

**Closed by Jehan** 2020-10-25 10:35 UTC
