### ISSUE TITLE
Can't open files inside ~/.var/local/com.valvesoftware.Steam/.../

### ISSUE THREAD

**Issue by JonasT** [flathub/org.gimp.GIMP#30] opened 2018-09-22 13:47 UTC
I can't open any image files inside `~/.var/local/com.valvesoftware.Steam/...` with Flatpak GIMP. The regularly installed one can browse into that folder just fine.

**Comment by JonasT** [comment] 2018-09-24 14:49
Thanks for the explanation, I already suspected it might supposed to be a security feature. However, GIMP has full disk access to my home folder, so it makes absolutely no sense to me that other flatpak installs would be notably less secure to access in addition. My home folder has much more personal and critical documents than any other folder.

Since I suspect this is the case for 99% of users, I would suggest this limitation does almost nothing for security, and mainly gets in the way of e.g. editing image files in the Steam folder. (Of course I still managed to do so by copying files around, but that is very annoying to do)

**Comment by Jehan** [comment] 2018-09-24 17:19
> However, GIMP has full disk access to my home folder, so it makes absolutely no sense to me that other flatpak installs would be notably less secure to access in addition.

This is up to discussion. ;-)
Also some could say that the current GIMP sandbox being too permissive currently, just considering this fatalistically, hence just adding more and more permission saying "*no reason to fight*" may not be the wisest. Maybe we should rather progressively improve the sandboxing (while keeping all features as much as possible).

Now I also completely understand your problematic. I am a bit frustrated myself by some parts of sandboxing and some parts of its implementations (in particular when it comes to files, for a software made to process files like GIMP, it becomes easily annoying when you can't access some files, or when folders get remapped, hence showing different paths on one software and the other for the same file, etc.). I also understand this may be needed more and more in the future (especially when you want to install some software less trusted than others).

Anyway let's wait for some of flatpak devs input here.

**Comment by TingPing** [comment] 2018-09-24 18:45
GIMP has `--filesystem=host`. Nothing in `home` is hidden or blocked in any way.

**Comment by Jehan** [comment] 2018-09-24 21:55
@TingPing As said in my first comment, I could confirm though that under `~/.var/app/`, the only folder I see in the flatpak GIMP is `org.gimp.GIMP/` (even though there are actually about a dozen folders there). I just retested again right now after seeing your comment.

So either something is blocked in some way (despite `--filesystem=host`) or if not on purpose, there is a bug somewhere (either in flatpak or in our manifest).

**Comment by TingPing** [comment] 2018-09-25 01:13
`flatpak run --filesystem=home --command=ls org.freedesktop.Platform//1.6 ~/.var/app` I see all apps here.

**Comment by Jehan** [comment] 2018-09-25 08:14
Indeed. Me too.

Unfortunately not in the GIMP sandbox:

```
$ flatpak run --command=ls org.gimp.GIMP//stable ~/.var/app
org.gimp.GIMP
```

Any idea what could go wrong?

**Comment by JonasT** [comment] 2018-09-25 11:16
For what it's worth, regarding the GIMP sandbox being insecure: I agree in so far that it's not what a user would expect for something advertised as "sandboxed". However, I think the main solution here would be a permission dialog like on Android and such, so that users can choose a custom amount of system access easily (and get an additional warning/confirmation dialog before the app gets full disk access).

**Comment by TingPing** [comment] 2018-09-25 12:30
> Unfortunately not in the GIMP sandbox:

That is very strange. Even removing all `filesystem` permissions other than `host` still behave the same. I think its safe to call it a Flatpak bug at least.

>  agree in so far that it's not what a user would expect for something advertised as "sandboxed". 

Mostly a GNOME-Software issue, it labels all Flatpaks (and Snaps?) sandboxed when it probably shouldn't.

**Comment by Jehan** [comment] 2019-02-28 22:54
Anyway so in the end, this is not a bug in our manifest. If bug there is, this is in flatpak.
I also confirmed that the same behavior was happening with other flatpak packages (the few ones I tried at least). So let's close this report. I opened one at flatpak instead: https://github.com/flatpak/flatpak/issues/2735

**Closed by Jehan** 2019-02-28 22:54 UTC
