### ISSUE TITLE
GIMP 2.10 appdata doesn't have icon tag

### ISSUE THREAD

**Issue by jgarciao** [flathub/org.gimp.GIMP#8] opened 2018-04-28 06:58 UTC
GIMP information in the flathub website is not being updated with the latest release info because there is not "icon"  tag in the appdata

https://flathub.org/apps/details/org.gimp.GIMP

If you look at /var/lib/flatpak/appstream/flathub/x86_64/active and unzip appstream.xml.gz you will find the data file where GIMP's entry lacks the icon tag. The flathub website parses this file to obtain its info

**Comment by jgarciao** [comment] 2018-04-28 12:42
Sorry, I don't know very much about how flatpak builds work. I've looked at the docs and other apps and they don't add anything like that in the APPNAME.appdata.xml.in file. Look at [org.gnome.Builder.appdata.xml.in](https://gitlab.gnome.org/GNOME/gnome-builder/blob/master/data/org.gnome.Builder.appdata.xml.in) for example

What I've seen is:

- Most of the apps have rename-icon in their build file to copy the icon with the proper name in the required place,  but [you do it already ](https://github.com/flathub/org.gimp.GIMP/blob/master/org.gimp.GIMP.json)

- The [app requirements](https://github.com/flathub/flathub/wiki/App-Requirements) specify that apps must have 64x64 and 128x128 icons at least, but your build doesn't provide icons with this resolutions. This might be the issue.  Look at this folder after installing org.gimp.GIMP:
`/var/lib/flatpak/app/org.gimp.GIMP/current/active/export/share/icons/hicolor`

If fixing that doesn't work maybe @nedrichards and @TingPing might know better what the problem is

**Comment by Jehan** [comment] 2018-04-28 12:53
Oh ok. I thought you knew exactly what would be the fix to the problem you were reporting.
Maybe @alexlarsson can help too.

**Comment by jgarciao** [comment] 2018-04-28 13:01
One more thing: 
```
flatpak search gimp
Application ID Version    Branch Remotes Description                       
org.gimp.GIMP  2.10.0~rc2 stable flathub Creeu imatges i editeu fotografies
```

The version is **rc2**. It could be possible that flathub doesn't have the latest version compiled? The build file uses [branch "GIMP_2_10_0"](https://github.com/flathub/org.gimp.GIMP/blob/145d5e37ac67dccdcfdd0151852b9f655e35bdcc/org.gimp.GIMP.app-modules.json#L37) but I think that's a git tag not a branch.

As I said, I don't know very much about how this works...

**Comment by TingPing** [comment] 2018-04-28 14:41
Appdata references desktop file, desktop file references icon.

**Comment by TingPing** [comment] 2018-04-28 14:42
You do correctly have ` <launchable type="desktop-id">gimp.desktop</launchable>`, and I *think* `"rename-desktop-file"` handles that..

**Comment by Jehan** [comment] 2018-04-28 14:43
> The version is rc2.

Thanks I opened a bug report to flatpak for this last issue: https://github.com/flatpak/flatpak/issues/1626

>  I think that's a git tag not a branch.

It's a tag indeed and has nothing to do with the wrong versionning you see. Flatpak does not generate versions from git tags.

**Comment by TingPing** [comment] 2018-04-28 14:44
> +  <icon type="stock">gimp</icon>

That seems wrong on multiple levels:

- Stock icons have been deprecated by Gtk since Gtk3
- "gimp" isn't a stock icon name.

**Comment by Jehan** [comment] 2018-04-28 14:50
> That seems wrong on multiple levels: […]

Ok. I just followed the advice on the bug description. I misunderstood and thought the reporter was sure that this was the solution.
I'll revert this since we already had the right thing (as I understand) regarding icons.

From what I understand, the issue raised by @jgarciao is that the application details in flathub is apparently outdated: https://flathub.org/apps/details/org.gimp.GIMP
And looking at it, looks true. Is there something to do on our side?

**Comment by jgarciao** [comment] 2018-04-28 15:04
Please, install gimp from flathub in your computer and go to the folder /var/lib/flatpak/appstream/flathub/x86_64/active. Unzip appstream.xml.gz and open the file "data". Then take a look at the GIMP component:
- it lacks the icon tag (I think because you don't ship 64x64 and 128x128 icons)
- there is not release-info for 2.10

**Comment by bochecha** [comment] 2018-04-28 15:56
> You do correctly have <launchable type="desktop-id">gimp.desktop</launchable>, and I think "rename-desktop-file" handles that..

It doesn't, last I checked.

**Comment by TingPing** [comment] 2018-04-28 16:14
> It doesn't, last I checked.

Well if that is the case then that is the problem.

**Comment by hughsie** [comment] 2018-05-02 08:56
You don't put icon information in the appdata file. It's read from the desktop file. I wonder if the flatpak was generated using the old appstream-glib that doesn't have the fixes of https://github.com/hughsie/appstream-glib/commit/f4bd5f611645eb394ac0419d848aba7fda91ccee

**Comment by Jehan** [comment] 2018-05-15 11:01
@hughsie From what I see, the freedesktop image uses appstream_glib 0.7.8 which contains this commit: https://github.com/flatpak/freedesktop-sdk-images/blob/1.6/org.freedesktop.Sdk.json.in#L2386
So that's probably not it. :-/

I just did some fixes in the appdata, hoping that would be it. But the metadata still doesn't show in flathub.
If I check the last build logs, it finds the appstream XML file, the id, etc. everything is a success. Still we get the old metadata and GIMP doesn't show as recently updated software on flathub.
Anyway the "update appdata" logs in particular are just 11 lines which just say that all is fine.
https://flathub.org/builds/#/builders/2/builds/1563

I am stumped. What is wrong in our appdata? Could anyone help? @alexlarsson ?

**Comment by TingPing** [comment] 2018-05-16 06:14
@Jehan 

- https://github.com/flathub/org.gimp.GIMP/issues/8#issuecomment-385181047
- https://github.com/flathub/org.gimp.GIMP/issues/8#issuecomment-385186143
- https://github.com/flathub/org.gimp.GIMP/issues/8#issuecomment-385187357

**Comment by Jehan** [comment] 2018-05-16 12:45
@TingPing Thanks. I saw these comments, and I already checked actually. Sorry, I should have written it down.

```
$ flatpak run --devel --command=bash org.gimp.GIMP//stable
$ ls /app/share/applications/org.gimp.GIMP.desktop 
/app/share/applications/org.gimp.GIMP.desktop
$ desktop-file-validate /app/share/applications/org.gimp.GIMP.desktop
$ echo $?
0
```

(and checking the contents, looks like the common desktop contents which we generate; looks all good)

> (GIMP doesn't build here (webkitgtk...) or else I would have tested this already)

Why wouldn't you add disable the module with:

```
"name": "webkitgtk",
"disabled": true,
```

I used to do this in my early tests of flatpak (either when I had issues building WebkitGTK, or simply because it just took too long and I wanted to test quicklier other parts of the manifest). This is an optional deps and can be disabled without any problem here. :-)

**Comment by Jehan** [comment] 2018-06-10 13:05
Anyone to help? As said, the desktop and appdata are both here.
```
$ flatpak run --devel --command=bash org.gimp.GIMP//stable
$ desktop-file-validate /app/share/applications/org.gimp.GIMP.desktop
$ appstream-util validate-relax /app/share/appdata/org.gimp.GIMP.appdata.xml
/app/share/appdata/org.gimp.GIMP.appdata.xml: OK
```

I tried various things, hoping that one would be the problem. The other day for instance, I removed all `<release>` (because the validate-strict was showing some style issues) as well as RC `<release>` (thinking that maybe a remnant of the sorting bug on appstream-glib may be there), but still no updated appdata on flathub nor on GNOME software.

I also notice these messages in my journalctl:
```
juin 09 04:03:23 DarkMarmot gnome-software[2115]: failed to add flatpak: org.gimp.GIMP not current, ignoring
juin 09 04:03:23 DarkMarmot gnome-software[2115]: tried overwriting org.gimp.GIMP.desktop key flatpak::Commit from bf6fc6d15e929c2d6c6a4211084e0f1f00>
juin 09 04:03:31 DarkMarmot gnome-software[2115]: failed to rescan: No valid root node specified
```

I am unsure of these. The first error seems like it may be ok. I indeed have several branches installed (and it looks like the meaning could be that it just bypass non-current flatpak). The last one though "No valid root node", could it be something we should look into?

Finally, for tests, if I copy `org.gimp.GIMP.appdata.xml` into `~/.local/share/metainfo/`, the metadata suddenly show into GNOME Software! This tends to imply that the file contents is fine and that all my attempts to tweak it are meaningless.

I don't know what else to do. Could someone from GNOME Software (@hughsie) or flatpak (@TingPing, @alexlarsson) help us understand where the problem is? We spent a long time to make a very complete Appdata file, following everyone's recommendation, and now that we have released, this file is basically used nowhere.

**Comment by jgarciao** [comment] 2018-06-12 08:31
I'm sorry you are still battling with this issue.

From the flathub.org website side, I will program a workaround in the code that parses the flathub appstream information in order to show the newest GIMP's information in the website, even if the appstream file doesn't have a icon tag

**Comment by Jehan** [comment] 2018-06-12 11:51
> even if the appstream file doesn't have a icon tag

Wait, are you still sure this is the reason why the appstream fails to load?
I thought we determined this was not the reason (cf. @hughsie comment: https://github.com/flathub/org.gimp.GIMP/issues/8#issuecomment-385909815 as well as some earlier @TingPing comments).

**Comment by Jehan** [comment] 2018-06-12 11:53
Also though I appreciate a workaround on flathub.org, I would really prefer to understand the problem and fix it, since it also happens on GNOME Software (and therefore likely on other similar application-parsing software).
Otherwise we may as well drop appdata if all our work filling this file is rendered useless.

**Comment by jgarciao** [comment] 2018-06-12 16:44
The latest build seem to have worked!

https://flathub.org/apps/details/org.gimp.GIMP

There is an issue with the release info appearing in multiple languages. I
think it's a big in the webapp that parses the repo info. I'll investigate
it this week

El dt., 12 de juny 2018, 13:53, Jehan <notifications@github.com> va
escriure:

**Comment by Jehan** [comment] 2018-06-12 21:36
> The latest build seem to have worked!

Indeed! The culprit was simply "rename-desktop-file" which is simply broken. It turns out there is already a bug report about this problem: https://github.com/flatpak/flatpak-builder/issues/155

> There is an issue with the release info appearing in multiple languages.

Yep saw this. Still it is minor compared to not have any data at all.

Anyway I will close this report now. It is good on our side for the time being with this patch. Hopefully you can fix the flatpak bug soon.

**Closed by Jehan** 2018-06-12 21:36 UTC
